version: '3.8'

volumes:
  source_code:

networks:
    apache_php:
    mysql_php:

services:
    database:
        container_name: prestashop_database
        image: 'mysql:5.7.33'
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - 'MYSQL_RANDOM_ROOT_PASSWORD=true'
            - 'MYSQL_DATABASE=prestashop'
            - 'MYSQL_USER=prestauser'
            - 'MYSQL_PASSWORD=prestapassword'
        networks:
            - mysql_php
        volumes:
            - './.docker/mysql/data:/var/lib/mysql:cached'
        expose:
            - 3306

    php-fpm:
        container_name: prestashop_php
        build:
            context: .
            dockerfile: './.docker/php-fpm/Dockerfile'
        depends_on:
            - database
        networks:
            - mysql_php
            - apache_php
        links:
            - database
        volumes:
            - './var/logs:/prestashop/logs:cached'
            - 'source_code:/prestashop'

    http:
        container_name: prestashop_apache
        build:
            context: './.docker/apache'
        depends_on:
            - php-fpm
        networks:
            - apache_php
        links:
            - php-fpm
        volumes:
            - 'source_code:/var/www/html'
